### ISSUE TITLE
Integerate pytest-expect with the hypothesis-pytest plugin

### ISSUE THREAD

**Issue by thedrow** [DRMacIver/hypothesis#131] opened 2015-08-23 09:59 UTC
[pytest-expect](https://github.com/gsnedders/pytest-expect) allows multiple assertions per test which is exactly what we need since we don't know how many tests are going to be run by hypothesis.

**Comment by DRMacIver** [comment] 2015-08-23 10:04
I really don't think it is, but perhaps you could expand on what you have in mind?

**Comment by thedrow** [comment] 2015-08-23 13:37
Sorry, I linked to the wrong plugin with the same name. Here it is https://github.com/okken/pytest-expect
This approach will allow you to run the test multiple times with multiple asserts. Maybe the code isn't in the best shape possible but even adapting the approach should provide us with what we need.

**Comment by The-Compiler** [comment] 2015-08-23 13:49
The tests only run once with this plugin, so I'm not sure how that'd help. The only thing the plugin provides is an assert-like thing which doesn't abort the test.

**Comment by thedrow** [comment] 2015-08-23 13:52
But the tests run with different inputs right? So if they do, they can use expect to provide reporting capabilities for each input.

**Comment by The-Compiler** [comment] 2015-08-23 14:03
Hypothesis already does take care of the reporting, so that doesn't solve anything. The issue is that hypothesis can't re-run the test multiple times and get fresh fixtures for every "sub-run".

**Comment by thedrow** [comment] 2015-08-23 15:43
I don't see any reports unfortunately. I only see when something fails.

**Comment by DRMacIver** [comment] 2015-08-26 07:50
There really doesn't seem to be anything here. I'm going to close this.

**Closed by DRMacIver** 2015-08-26 07:50 UTC
