### ISSUE TITLE
"assume" in an always failing test gives hypothesis.errors.UnsatisfiedAssumption

### ISSUE THREAD

**Issue by palfrey** [DRMacIver/hypothesis#253] opened 2015-12-27 19:11 UTC
So, I've been tinkering around with Hypothesis the last few days, and I've run into a fun one. In a couple of cases I've had a test that should always throw an exception because I've broken something in the code it's testing *and* has an `assume` statement at the beginning of the test function, I get a hypothesis.errors.UnsatisfiedAssumption not the expected Exception. Fixing the broken code makes the test pass, but I'd much rather have the exception to make my life easier when fixing the code...

I suspect a chunk of this is that I'm doing something a bit daft - testing a heavily stateful interface without use of `RuleBasedStateMachine` yet - and the `assume` is of the form "don't do a duplicate insert of an item with one of these ids that needs to be unique", so it may be failing due to trying to simplify something it can't run twice, but I'd still expect this to throw the Exception.

I'm using Hypothesis 1.18.1 from pypi on Python 3.5.0 on OS X

**Comment by DRMacIver** [comment] 2015-12-27 19:13
That definitely shouldn't be happening. Could you give me an example to reproduce the problem please?

**Comment by palfrey** [comment] 2015-12-27 20:42
```python
import unittest
from hypothesis import given, assume
import hypothesis.strategies as st

class Foo(unittest.TestCase):
	def setUp(self):
		self.existing = []

	@given(st.integers())
	def test_assumptions_fail(self, s):
		assume(s not in self.existing)
		self.existing.append(s)
		raise Exception
```

**Comment by DRMacIver** [comment] 2015-12-27 20:47
Oh, I see. You definitely shouldn't be doing that. setUp is only called once per test, not once per example. I agree that the error produced when you do is super confusing though, and that should be fixed.

**Comment by DRMacIver** [comment] 2015-12-27 20:50
To clarify: The problem is that when Hypothesis tries to recreate the failure it saw, an example that previously satisfied your assumptions no longer does.

**Comment by palfrey** [comment] 2015-12-27 21:28
Ah. So, in other words, do tests need to be idempotent? I'd sort of picked that up vaguely from the documentation, but wasn't clearly spelt out at any point.

**Comment by DRMacIver** [comment] 2015-12-27 21:36
Yes. Tests shouldn't depend on any external state.

**Comment by DRMacIver** [comment] 2015-12-27 21:38
You're right that this should be better documented.

**Comment by DRMacIver** [comment] 2016-01-07 11:36
This will now correctly raise a Flaky error as of 087d85d9ad65a29dff15aefe6106aa534c08325b with a message that explains what's going wrong.

**Closed by DRMacIver** 2016-01-07 11:36 UTC
