### ISSUE TITLE
fake-factory fails when given a sources that is not available in all locales

### ISSUE THREAD

**Issue by davidrusu** [DRMacIver/hypothesis#105] opened 2015-07-21 14:32 UTC
An AttributeError is raised when fake_factory is given a source that is not available in all locales

``` python
from faker import Faker
fake = Faker()
fake.state() # -> 'Ohio'

from hypothesis.extra.fakefactory import fake_factory
fake_factory('state').example() # -> AttributeError: 'Generator' object has no attribute 'state'
```
If we include ```locale='en_US'``` it works fine
``` python
fake_factory('state', locale='en_US').example() # -> 'New York'
```
When given a source that doesn't exist, we get a ValueError as expected
``` python
fake_factory('Not A Source').example() # -> ValueError: No such source 'Not A Source'
```

BTW, thanks for this awesome tool

**Comment by DRMacIver** [comment] 2015-07-21 22:17
If you upgrade to hypothesis-fakefactory 0.14.1 this should be fixed.

As a bonus, you might also find your performance problems have gone away. If you're using fake-factory heavily that might have been the cause of them - there was a significant performance bug in the implementation.

**Closed by DRMacIver** 2015-07-21 22:17 UTC
