### ISSUE TITLE
Slow shrinking gives poor dev experience

### ISSUE THREAD

**Issue by james-w** [DRMacIver/hypothesis#231] opened 2015-12-08 19:08 UTC
Hi,

I've been trying out hypothesis today, and found a rough edge.

I have a strategy for producing a recursive data structure. I am
using it in a test. I am writing this while waiting for the test to
return, so far it has been 10 minutes.

If I set max_shrinks=0 then run again I get a failure near-instantly.

I suspect that it is having trouble shrinking the example.
(My uneducated guess is that the *structure* matters a lot
for the test, but all the internal details don't, so it is trying
a lot of examples that tinker with the internal values that
have no bearing on the test.)

I've read that hypothesis has a default timeout of 60s,
but that doesn't seem to apply to shrinking.

Overall while it's great that it is finding interesting cases
for me, the fact that it isn't showing them to me isn't helpful.
I'd prefer a larger example now to a smaller one in 10 minutes.

Some possible ideas:

  * apply the timeout the shrinking stage too.
  * reduce the default max_shrinks.
  * when an example is found show that to the user, and then attempt to shrink it. They can puzzle on the unshrunk version while it works.

Thanks for working on this.

James

**Comment by james-w** [comment] 2015-12-08 19:14
In fact max_shrinks=1 doesn't return fast either, so I suspect that it is failing to shrink at all.

Is there a limit on how long it will look for shrinks before giving up? Does max_iterations
apply to shrinking too?

**Comment by DRMacIver** [comment] 2015-12-08 19:15
I agree this is problematic. I'm working on some things that should improve matters for shrinking performance.

Some notes:

* The timeout does apply to the shrinking stage. I'm not sure why you're seeing it taking 10 minutes. That might be a bug. I'd be interested in an example where this happens if you can share.
* Even if it's not, what you're experiencing is very atypically slow. Some of the problem here is probably the recursive example, but even then it's very rare for it to be that slow. The normal max_shrinks is rarely a problem for most examples.
* It's almost impossible to show things to the user prior to shrinking due to the way Python's test frameworks work. 

I don't think it's very likely, but one possibility is that sometimes new bugs occur during shrinking, and it might be that one of those bugs is triggering an infinite loop in your own code. The timeout is soft, so if an individual test never returns or takes a very long time to return it won't be terminated prematurely.

One thing you could try is set the environment variable HYPOTHESIS_VERBOSITY_LEVEL=verbose to see what it's doing (you'll need to turn off output capturing in py.test or nose as well)

**Comment by DRMacIver** [comment] 2015-12-08 19:16
Hm. That's interesting. You're right, there's probably nothing that stops it if no shrinks at all succeed.

It's very strange that that would happen in a case that where there are also a lot of shrinks that could be performed. Are you sure there's not a bug in your test where it depends on external state?

**Comment by james-w** [comment] 2015-12-08 19:38
Hi,

Thanks for taking a look.

I've pushed up my WIP to https://github.com/james-w/notlang/tree/hypothesis (hypothesis branch). You *may* be able to run it with

  make deps
  make test TEST_FILTER=test_parsing

but you would be the second person ever to try.

Running with verbose and a few other tweaks show that it isn't running many examples. It appears
my uneducated guess as to the cause was unsurprisingly wrong. As I write it is sitting thinking using
1 core, but not running any examples, and apparently still looking for a failure (when I would have
thought the db would have one currently).

You can see the test here:

  https://github.com/james-w/notlang/blob/hypothesis/notlang/tests/test_parsing.py#L599

and the strategies here:

  https://github.com/james-w/notlang/blob/hypothesis/notlang/testing/strategies/ast.py

It could well be that my strategy implementations are terrible.

Thanks,

James

**Comment by DRMacIver** [comment] 2015-12-08 19:47
I'll probably not have time to try running this tonight, but I'll take a look tomorrow.

Looking at this though... what you're probably running into right now is that Hypothesis is trying to produce some huge examples and is behaving rather poorly when it does. You might find it useful to apply some average_size arguments to the lists, text, etc and see if that helps.

The large examples thing is a bit of a problem with the current implementation of Hypothesis and making it behave better should fall out of my current line of R&D.

**Comment by DRMacIver** [comment] 2015-12-09 09:14
So I've had a bit of a look into this (side note: The only thing I had to change about your makefile was to replace the hardcoded /usr/bin/pypy with $$(which pypy)) .

If you set average_size=2.0 in all your lists, the performance goes from "intolerably slow" to "really slow".

If you also set max_leaves=10 on all your recursive calls it becomes pretty OK - the generation is now acceptably fast, the shrinking takes up to about a minute, and example saving is speedy so rerunning with a shrunk example only takes a couple seconds.

In general the problem here is basically that the strategy you've constructed generates *huge* values and Hypothesis doesn't cope with that very well or automatically detect that it needs to handle that. See #166 for the issue about the fact that it needs to do this.

I think between #166, #233  and #232 this is covered, so I'm inclined to close this if you agree?

**Comment by james-w** [comment] 2015-12-09 10:32
Hi,

Thanks for looking in to this, I've made the suggested changes and will
see how it works.

I agree that this issue can be closed.

Thanks,

James

**Closed** 2015-12-09 10:40 UTC
